import "./styles.css"

export { default as UiMenu } from "./components/UiMenu.vue"
export { default as UiMenuTrigger } from "./components/UiMenuTrigger.vue"
export { default as UiMenuContent } from "./components/UiMenuContent.vue"
export { default as UiMenuItem } from "./components/UiMenuItem.vue"
export { default as UiMenuLabel } from "./components/UiMenuLabel.vue"
export { default as UiMenuSeparator } from "./components/UiMenuSeparator.vue"
export { default as UiSubMenu } from "./components/UiSubMenu.vue"
export { default as UiSubMenuTrigger } from "./components/UiSubMenuTrigger.vue"
export { default as UiSubMenuContent } from "./components/UiSubMenuContent.vue"

export * from "@affino/menu-core"
export * from "./useMenu"
export * from "./context"
export { useMenuShortcuts, matchesShortcut } from "./useMenuShortcuts"
