packages:
  - packages/*
  - demo-vue
  - demo-laravel
  - docs-site

overrides:
  vue: 3.4.38
  "@vue/runtime-core": 3.4.38
  "@vue/runtime-dom": 3.4.38
  "@vue/reactivity": 3.4.38
  "@vue/shared": 3.4.38
  "@vue/compiler-core": 3.4.38
  "@vue/compiler-dom": 3.4.38
  "@vue/compiler-sfc": 3.4.38
  "@vue/server-renderer": 3.4.38
  braces: ^3.0.3
  minimatch: ^10.2.3
  serialize-javascript: ^7.0.3
  preact: ^10.28.2
  micromatch: ^4.0.8
  esbuild: ^0.25.0
  rollup: ^4.59.0
  qs: ^6.15.0
  "ajv@^8.0.0": ^8.18.0
  "ajv@^6.0.0": ^6.14.0

onlyBuiltDependencies:
  - "@swc/core"
  - esbuild
  - unrs-resolver

allowBuilds:
  '@swc/core': true
  esbuild: true
  unrs-resolver: true
